### ISSUE TITLE
Capsule events from randomizer logic/code

### ISSUE THREAD

**Issue by AECX** [zsrtp/Randomizer#10]
https://github.com/zsrtp/Randomizer/blob/ae665953215b412a55c6ed8dc317a674b93d1b25/GameCube/source/events.cpp#L27-L32

Move this into the Randomizer class (like with onLoad) so future classes can simply call their respective handler without specific code inside the Event Class (Single Responsibility Principle)

**Comment by lunarsoap5** [comment]
This issue was resolved with a change in Randomizer architecture.
