### ISSUE TITLE
Saving and quiting then exiting Dolphin resets golden bug item checks

### ISSUE THREAD

**Issue by LogiGameStar** [zsrtp/Randomizer#11]
When I saved then stopped playing then came back later. I picked up some of the golden bugs I had already picked up and I ended up getting duplicate items. For example, I got a bottle of milk from one gold bug then another from the same gold bug. I also got an Ordan Sword then later got the Master Sword from the exact same gold bug. This bug only happens if you turn off the game: It does not happen if you just save and quit then go back in to your file. I tested it with the bug that gave me the bottle.

**Comment by lunarsoap5** [comment]
This is a known issue in the beta (the code for which can be found here: https://github.com/zsrtp/GC-Randomizer). This issue does not exist in this repository, which is for the version 1.0 code so I will close this issue. If you have any other issues with the beta version of the randomizer, please send it in the #bug-reports channel of the discord (https://www.discord.zeldatp.net).
