### ISSUE TITLE
Hyrule Field lags on Dolphin

### ISSUE THREAD

**Issue by alkaris2** [zsrtp/Randomizer#3]
Is there any way you could implement the Hyrule Field Speed Hack with this randomizer? Because without it the game will lag heavily when in Hyrule Field on Dolphin emulator. I have tried to use the already provided Hyrule Field Speed Hack game patch, but I've come to learn that enabling this game patch before starting the game makes the randomizer on a current save files and reverts to stock Twilight Princess gameplay, it pretty much breaks the randomizer so that items aren't randomized anymore.

**Comment by lunarsoap5** [comment]
There are no compatibility issues between the Field Patch and the randomizer. If you are needing help to get it to work, I advise that you to join the discord and ask for help there. https://discord.zeldatp.net

**Comment by Chris-Is-Awesome** [comment]
I've used speed patch with rando since the beginning, has never caused issues with any version of rando. So it might be worth trying a different Dolphin version? Could be that something's weird with that version.
